### ISSUE TITLE
Patch for /trunk/EsperantoRadio/res/raw/esperantoradio_kanaloj_v2.json

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nordfalk/esperanto-telefono#1]
```
 saluton
```

Original issue reported on code.google.com by `rogier.h...@gmail.com` on 20 Dec 2011 at 1:45

**Comment by nordfalk** [comment]
Saluton Rogier,

Ĉu vi volis plibonigi ion?
Provu denove :-)

Kore,
Jacob
