### ISSUE TITLE
Patch for /trunk/EsperantoRadio/res/values/strings.xml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nordfalk/esperanto-telefono#2]
```
Mi plibonigis iomete la kvaliton de la teksto kune kun Peter Weide.
```

Original issue reported on code.google.com by `jodi80...@gmail.com` on 18 Nov 2012 at 7:34

Attachments:
- [strings.xml.patch](https://storage.googleapis.com/google-code-attachments/esperanto-telefono/issue-2/comment-0/strings.xml.patch)

**Comment by nordfalk** [comment]
Dankon por la proponoj. Tiuj tekstoj nun ne plu estas uzataj.
